version: '3'

services:
  sense:
    build: "./src/sense"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - "./src:/airmon"
    environment:
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
  web:
    build: "./src/web"
    volumes:
      - "./src:/airmon"
    ports:
      - "5000:5000"
    environment:
      - DB_NAME
      - DB_USERNAME
      - DB_PASSWORD
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  db:
